In [1]:
import pandas as pd

In [2]:
pd.__version__

'1.5.3'

In [3]:
A = pd.Series([1, 2, 3, 4], index =['a', 'b', 'c', 'd'])

In [4]:
A

a    1
b    2
c    3
d    4
dtype: int64

In [5]:
type(A)

pandas.core.series.Series

In [6]:
A.values

array([1, 2, 3, 4], dtype=int64)

In [7]:
type(A.values)

numpy.ndarray

In [8]:
A.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [9]:
A['d']

4

In [10]:
A['a': 'c']  #it is implicit indeces where the final index also counts

a    1
b    2
c    3
dtype: int64

In [11]:
A[1: 2] #it is implicit indeces

b    2
dtype: int64

In [27]:
grad_dict = {'A':4, ' A-':3.5, 'B':3, ' B-':2.5, 'B':2}

In [13]:
grades = pd.Series(grad_dict)

In [14]:
grades

A     4.0
A-    3.5
B     2.0
B-    2.5
dtype: float64

In [15]:
grad_dict

{'A': 4, 'A-': 3.5, 'B': 2, 'B-': 2.5}

In [16]:
grades.values

array([4. , 3.5, 2. , 2.5])

In [17]:
grades['A']

4.0

In [19]:
grades['A': 'B']

A     4.0
A-    3.5
B     2.0
dtype: float64

In [20]:
grades[0: 2]

A     4.0
A-    3.5
dtype: float64

In [26]:
marks_dict = {'A':85, ' A-':80, 'B':75, ' B-':70, 'B':65}

In [22]:
marks = pd.Series(marks_dict)

In [23]:
marks

A     85
A-    80
B     65
B-    70
dtype: int64

In [28]:
df = pd.DataFrame({'grades': grades, 'marks': marks})

In [29]:
df

grades  marks
A      4.0     85
A-     3.5     80
B      2.0     65
B-     2.5     70

In [30]:
df.T

A    A-     B    B-
grades   4.0   3.5   2.0   2.5
marks   85.0  80.0  65.0  70.0

In [32]:
df.values

array([[ 4. , 85. ],
       [ 3.5, 80. ],
       [ 2. , 65. ],
       [ 2.5, 70. ]])

In [34]:
df.values[3,1]

70.0

In [35]:
df.columns

Index(['grades', 'marks'], dtype='object')

In [36]:
df

grades  marks
A      4.0     85
A-     3.5     80
B      2.0     65
B-     2.5     70

In [37]:
df.index

Index(['A', 'A-', 'B', 'B-'], dtype='object')

In [43]:
df['percentage'] = 100*(df['marks']/90)

In [44]:
df

grades  marks  percentage
A      4.0     85   94.444444
A-     3.5     80   88.888889
B      2.0     65   72.222222
B-     2.5     70   77.777778

In [46]:
del df['percentage']

In [47]:
df

grades  marks
A      4.0     85
A-     3.5     80
B      2.0     65
B-     2.5     70

In [52]:
D = df[df['marks'] > 70]

In [53]:
D

grades  marks
A      4.0     85
A-     3.5     80

## NaN values in pandas

In [54]:
B = pd.DataFrame([{'a': 1, 'b': 4}, {'b':5, 'c': 7}])

In [55]:
B

a  b    c
0  1.0  4  NaN
1  NaN  5  7.0

In [56]:
B.fillna(0)

a  b    c
0  1.0  4  0.0
1  0.0  5  7.0

In [57]:
# loc explicit index
# iloc implicit index

In [60]:
C = pd.Series(['a', 'b', 'c'], index=[1,3,5])

In [61]:
C

1    a
3    b
5    c
dtype: object

In [62]:
C[1]

'a'

In [63]:
C[1:3]

3    b
5    c
dtype: object

In [64]:
C.loc[1:3]

1    a
3    b
dtype: object

In [65]:
C.iloc[1:3]

3    b
5    c
dtype: object

In [66]:
df

grades  marks
A      4.0     85
A-     3.5     80
B      2.0     65
B-     2.5     70

In [67]:
df.iloc[3:]

grades  marks
B-     2.5     70

In [68]:
df.iloc[:]

grades  marks
A      4.0     85
A-     3.5     80
B      2.0     65
B-     2.5     70

In [69]:
df.iloc[:3]

grades  marks
A      4.0     85
A-     3.5     80
B      2.0     65

In [72]:
df.iloc[0:0]

Empty DataFrame
Columns: [grades, marks]
Index: []

In [76]:
df.iloc[::]

grades  marks
A      4.0     85
A-     3.5     80
B      2.0     65
B-     2.5     70

In [77]:
df.iloc[::-1]

grades  marks
B-     2.5     70
B      2.0     65
A-     3.5     80
A      4.0     85

In [79]:
from sklearn.impute import SimpleImputer

In [81]:
df1 = pd.read_csv('D:\Learn Python\Python for Data science\Covid19 datset\country_wise_latest.csv')

In [85]:
df1.head()

Country/Region  Confirmed  Deaths  Recovered  Active  New cases  New deaths  \
0    Afghanistan      36263    1269      25198    9796        106          10   
1        Albania       4880     144       2745    1991        117           6   
2        Algeria      27973    1163      18837    7973        616           8   
3        Andorra        907      52        803      52         10           0   
4         Angola        950      41        242     667         18           1   

   New recovered  Deaths / 100 Cases  Recovered / 100 Cases  \
0             18                3.50                  69.49   
1             63                2.95                  56.25   
2            749                4.16                  67.34   
3              0                5.73                  88.53   
4              0                4.32                  25.47   

   Deaths / 100 Recovered  Confirmed last week  1 week change  \
0                    5.04                35526            737   
1                    5.25                 4171            709   
2                    6.17                23691           4282   
3                    6.48                  884             23   
4                   16.94                  749            201   

   1 week % increase             WHO Region  
0               2.07  Eastern Mediterranean  
1              17.00                 Europe  
2              18.07                 Africa  
3               2.60                 Europe  
4              26.84                 Africa

In [90]:
df1.drop(['New cases', 'New deaths','New recovered', 'Deaths / 100 Cases', 'Recovered / 100 Cases', 'Deaths / 100 Recovered','Confirmed last week', '1 week change','1 week % increase' ], axis=1, inplace=True)
df1.head()

Country/Region  Confirmed  Deaths  Recovered  Active
0    Afghanistan      36263    1269      25198    9796
1        Albania       4880     144       2745    1991
2        Algeria      27973    1163      18837    7973
3        Andorra        907      52        803      52
4         Angola        950      41        242     667

In [91]:
df1.rename(columns={'Country/Region': 'Country', 'Confirmed': 'Confirmed Cases', 'Recovered': 'Recovered Cases', 'Active': 'Active Patients' }, inplace=True)

In [92]:
df1.head()

Country  Confirmed Cases  Deaths  Recovered Cases  Active Patients
0  Afghanistan            36263    1269            25198             9796
1      Albania             4880     144             2745             1991
2      Algeria            27973    1163            18837             7973
3      Andorra              907      52              803               52
4       Angola              950      41              242              667

In [93]:
df1.describe()

Confirmed Cases         Deaths  Recovered Cases  Active Patients
count     1.870000e+02     187.000000     1.870000e+02     1.870000e+02
mean      8.813094e+04    3497.518717     5.063148e+04     3.400194e+04
std       3.833187e+05   14100.002482     1.901882e+05     2.133262e+05
min       1.000000e+01       0.000000     0.000000e+00     0.000000e+00
25%       1.114000e+03      18.500000     6.265000e+02     1.415000e+02
50%       5.059000e+03     108.000000     2.815000e+03     1.600000e+03
75%       4.046050e+04     734.000000     2.260600e+04     9.149000e+03
max       4.290259e+06  148011.000000     1.846641e+06     2.816444e+06

In [94]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Country          187 non-null    object
 1   Confirmed Cases  187 non-null    int64 
 2   Deaths           187 non-null    int64 
 3   Recovered Cases  187 non-null    int64 
 4   Active Patients  187 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 7.4+ KB


In [98]:
df2 = df1[df1['Confirmed Cases']>1000]
df2.head()

Country  Confirmed Cases  Deaths  Recovered Cases  Active Patients
0  Afghanistan            36263    1269            25198             9796
1      Albania             4880     144             2745             1991
2      Algeria            27973    1163            18837             7973
6    Argentina           167416    3059            72575            91782
7      Armenia            37390     711            26665            10014