## Numpy(Boradcasting)

In [1]:
import numpy as np

In [3]:
A = np.round(10*np.random.rand(2,3))

In [4]:
A

array([[10.,  9., 10.],
       [ 6.,  0.,  7.]])

In [5]:
A + 5

array([[15., 14., 15.],
       [11.,  5., 12.]])

## np.hstack 
## np.vstack 
## np.sort

In [10]:
A + (np.arange(2).reshape(2,1))

array([[10.,  9., 10.],
       [ 7.,  1.,  8.]])

In [11]:
A

array([[10.,  9., 10.],
       [ 6.,  0.,  7.]])

In [12]:
B = np.round(10*np.random.rand(2,2))

In [13]:
B

array([[7., 4.],
       [6., 7.]])

In [14]:
C = np.hstack((A,B))

In [15]:
C

array([[10.,  9., 10.,  7.,  4.],
       [ 6.,  0.,  7.,  6.,  7.]])

In [18]:
D = np.random.permutation(np.arange(10))

In [19]:
D

array([0, 6, 7, 8, 5, 2, 9, 4, 3, 1])

In [22]:
D.sort()

In [23]:
D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.sort(D)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
S = D[::-1] #sort decesnding order

In [27]:
S

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [28]:
S = np.array(["abc", "124", "she", "zoo", "how"])

In [29]:
S.sort()

In [30]:
S

array(['124', 'abc', 'how', 'she', 'zoo'], dtype='<U3')

## how fast the Numpy is, let's check

In [31]:
B = np.random.rand(1000000)

In [32]:
%timeit sum(B)

109 ms ± 20.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [33]:
%timeit B.sum()

1.62 ms ± 89.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [34]:
%timeit np.sum(B)

1.65 ms ± 62.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [35]:
def mysum(G):
    s = 0
    for x in G:
        s+=x
        return s

In [36]:
%timeit mysum(B)

355 ns ± 35.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
