## Numpy Slicing

# b = a[1:5] this b is not a copy of a actualy it is accessing the same memory view as an a if you change any element in b the element in a will change as long a is an numpy array, however if the a is list or any other data structute than b is a copy of a, numpy array is mutable changable

In [1]:
import numpy as np

In [3]:
a = np.arange(20)

In [4]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
b = a[2:10]

In [6]:
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b[0] = -20

In [8]:
b

array([-20,   3,   4,   5,   6,   7,   8,   9])

In [9]:
a

array([  0,   1, -20,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [22]:
idx = np.argwhere(a==-20)[0][0]

In [23]:
idx

2

In [24]:
a[idx] = 2

In [25]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# if you dont want to change the elements of a from b than use copy
c = np.arange(100)

In [14]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
d = c[2:10].copy # like this

In [19]:
c[::5] # will pick every 5the elements starts from zero till end and than pick only 5th

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [20]:
c[::-5] # reversly starts from 2nd go to the start and pick only 5th from reverse

array([99, 94, 89, 84, 79, 74, 69, 64, 59, 54, 49, 44, 39, 34, 29, 24, 19,
       14,  9,  4])

In [21]:
c[::-1] # reverse whole array

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [28]:
a = np.round(10*np.random.rand(5, 4))

In [29]:
a

array([[ 6.,  1.,  5.,  7.],
       [ 8.,  1.,  2.,  9.],
       [10.,  9.,  9.,  5.],
       [ 9.,  7., 10.,  9.],
       [ 1.,  1.,  4.,  4.]])

In [30]:
a[2, 2]

9.0

In [31]:
a[1]

array([8., 1., 2., 9.])

In [33]:
a[1,:]

array([8., 1., 2., 9.])

In [35]:
a[:,2]

array([ 5.,  2.,  9., 10.,  4.])

In [36]:
a

array([[ 6.,  1.,  5.,  7.],
       [ 8.,  1.,  2.,  9.],
       [10.,  9.,  9.,  5.],
       [ 9.,  7., 10.,  9.],
       [ 1.,  1.,  4.,  4.]])

In [39]:
a[1:3, 2:4]

array([[2., 9.],
       [9., 5.]])

In [40]:
a.T

array([[ 6.,  8., 10.,  9.,  1.],
       [ 1.,  1.,  9.,  7.,  1.],
       [ 5.,  2.,  9., 10.,  4.],
       [ 7.,  9.,  5.,  9.,  4.]])

In [41]:
a.sort(axis=0) #sort every column
a

array([[ 1.,  1.,  2.,  4.],
       [ 6.,  1.,  4.,  5.],
       [ 8.,  1.,  5.,  7.],
       [ 9.,  7.,  9.,  9.],
       [10.,  9., 10.,  9.]])

In [42]:
a.sort(axis=1) #sort every row
a

array([[ 1.,  1.,  2.,  4.],
       [ 1.,  4.,  5.,  6.],
       [ 1.,  5.,  7.,  8.],
       [ 7.,  9.,  9.,  9.],
       [ 9.,  9., 10., 10.]])

## Numpy(More Indexing)

In [43]:
A = np.arange(100)

In [44]:
B = A[[3, 5, 6]]

In [45]:
B

array([3, 5, 6])

In [46]:
B[0] = -1

In [47]:
B # result is copy rather thana view

array([-1,  5,  6])

In [48]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [49]:
B = A[A<40]

In [50]:
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [51]:
B = A[(A<40) & (A>30)]

In [52]:
B

array([31, 32, 33, 34, 35, 36, 37, 38, 39])

# and = both sides are single objects, & both sides are different arrays
# arrays  not arrays
# &       and
# /       or
# ~       not